name : PureTickets
main : broccolai.tickets.bukkit.BukkitPlatform
version : $version
api-version : 1.13

permissions :
  tickets.user.* :
    default : true
    description : Allows access to all ticket user permissions
    children :
      tickets.user : true
      tickets.user.create : true
      tickets.user.update : true
      tickets.user.close : true
      tickets.user.show : true
      tickets.user.list : true
      tickets.user.log : true
  tickets.user.create :
    default : true
    description : Allows a user to create a ticket
  tickets.user.update :
    default : true
    description : Allows a user to update a ticket
  tickets.user.close :
    default : true
    description : Allows a user to close a ticket
  tickets.user.show :
    default : true
    description : Allows a user to close a ticket
  tickets.user.list :
    default : true
    description : Allows a user to close a ticket
  tickets.user.log :
    default : true
    description : Allows a user to close a ticket
  tickets.staff.* :
    default : op
    description : Allows access to all ticket staff permissions
    children :
      tickets.staff : true
      tickets.staff.show : true
      tickets.staff.claim : true
      tickets.staff.assign : true
      tickets.staff.done : true
      tickets.staff.unclaim : true
      tickets.staff.reopen : true
      tickets.staff.teleport : true
      tickets.staff.log : true
      tickets.staff.list : true
      tickets.staff.announce : true
      tickets.staff.remind : true
      tickets.staff.highscore : true
  tickets.staff.show :
    default : op
    description : Allows a user to view a ticket
  tickets.staff.claim :
    default : op
    description : Allows a user to claim a ticket
  tickets.staff.assign :
    default : op
    description : Allows a user to assign a ticket to someone
  tickets.staff.done :
    default : op
    description : Allows a user to done-mark a ticket
  tickets.staff.unclaim :
    default : op
    description : Allows a user to unclaim a ticket
  tickets.staff.reopen :
    default : op
    description : Allows a user to reopen a ticket
  tickets.staff.teleport :
    default : op
    description : Allows a user to teleport to a ticket
  tickets.staff.log :
    default : op
    description : Allows a user to view a tickets messages
  tickets.staff.list :
    default : op
    description : Allows a user to view all open tickets
  tickets.staff.announce :
    default : op
    description : Allows a user to see when a ticket is changed
  tickets.staff.remind :
    default : op
    description : Allows a user to view the ticket reminder message
  tickets.staff.highscore :
    default : op
    description : Allows a user to view highscores of ticket completions
