name: "tickets"
version: "$version"
main: "love.broccolai.tickets.minecraft.paper.PaperTicketsPlugin"
loader: "love.broccolai.tickets.lib.xyz.jpenilla.gremlin.runtime.platformsupport.DefaultsPaperPluginLoader"
api-version: "1.20"
