---
spring:
    profiles:
        active: local

    application:
        name: tickets-spring

    main:
        log-startup-info: false
        banner-mode: off

    mvc:
        converters:
            preferred-json-mapper: gson
