name: "build"

on:
    push:
    pull_request:
    release:
        types: [ released ]
        
defaults:
    run:
        working-directory: ./plugin
            
jobs:
    call-build:
        uses: "broccolai/actions/.github/workflows/shared-ci.yml@master"
        secrets: inherit
        with:
            artifacts-path: 'build/libs/tickets-paper.jar'
