name: java release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./plugin

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/tickets-paper.jar
          asset_name: tickets-bukpaperkit.jar
          asset_content_type: application/java-archive